In [2]:
import torch
print("CUDA Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("Memory Allocated:", torch.cuda.memory_allocated(0))

CUDA Available: True
GPU Name: NVIDIA GeForce RTX 5090
Memory Allocated: 0


In [3]:
import json
import networkx as nx
from sklearn.preprocessing import OneHotEncoder
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam
from torch. utils.data import Dataset
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import MessagePassing, global_mean_pool
from pymatgen.io.cif import CifParser
from pymatgen.core import Structure, Element

group_number = 18
row_number = 7
X_class_number = 10
r_class_number = 10
node_dim = group_number + row_number + X_class_number + r_class_number

distance_class_number = 10
edge_dim = distance_class_number

learned_dim = 20


# Step 1 Data Preparation

- Use pymatgen to load the json_gz file and pretty print the content




## dataset

- Input matrix should contains information about nodes and edges.



In [4]:
import numpy as np
path = './matbench_phonons.json/phonons.json'

class DataTransform(Dataset):
    def __init__(self, path, normalize = True):
        super().__init__()
        with open(path) as f:
            obj = json.load(f)
        self.index = obj["index"]
        self.data = obj["data"]
        max_index = max(self.index) + 1 if self.index else 0
        self.struct_list = [None] * max_index    
        for idx, data_item in zip(self.index, self.data):
            self.struct_list[idx] = Structure.from_dict(data_item[0])
        
        self.normalize = normalize
        if self.normalize:
            all_labels = [self.data[idx][1] for idx in self.index]
            self.label_mean = np.mean(all_labels)
            self.label_std = np.std(all_labels)
        else:
            self.label_mean = 0.0
            self.label_std = 1.0

    def __len__(self):  # 必须实现
        return len(self.index)
    
    def build_node(self, idx):
        struct = self.struct_list[idx]
        tensor_list = []
        for site in struct.sites:
            element = Element(site.specie.symbol)
            radius = element.atomic_radius * 100  # convert to pm
            # OneHot encoding with group and row:
            group = element.group
            row = element.row
            X = element.X
            # OneHot encoding with group and row:
            group = F.one_hot(torch.tensor(group - 1), num_classes=18).float()
            row = F.one_hot(torch.tensor(row - 1), num_classes=7).float()
            if(25<=radius<250):
                radius = F.one_hot(torch.tensor(int((radius - 25)/22.5)), num_classes=10).float()
            else:
                radius = torch.zeros(10)
            if (X < 0.5 or X >= 4.0):
                X =torch.zeros(10)
            else:
                X = F.one_hot(torch.tensor(int((X - 0.5) / 0.35)), num_classes=10).float()
            # concate group and row features
            node_feat = torch.cat([group, row, X, radius], dim=0)
            # print(node_feats): 
            # tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # group 8
            #         0, 0, 1, 0, 0, 0, 0,        # row 3
            #         0, 0, 0, 0, 1, 0, 0, 0, 0, 0])          # X
            
            # concate group and row features 
            
            tensor_list.append(node_feat)
        node_feats = torch.stack(tensor_list, dim=0)
        return node_feats
    
    def build_edge(self, idx, cutoff=5.0):
        struct = self.struct_list[idx]
        num_atoms = len(struct.sites)
        nbrs = struct.get_all_neighbors(cutoff)
        tensor_list = []
        edge_index = torch.zeros((2,0), dtype=torch.long)
        for center_idx, neighbors in enumerate(nbrs):
            for neighbor in neighbors:
                distance = neighbor.nn_distance
                if (distance < 0.7 or distance >= 5.2):
                    distance = torch.zeros(10)
                else:
                    distance = F.one_hot(torch.tensor(int((distance-0.7)/0.45)), num_classes=10).float()
                tensor_list.append((distance))
                edge_index = torch.cat([edge_index, torch.tensor([[center_idx],[neighbor.index]])], dim=1)
            
        edge_fea = torch.stack(tensor_list, dim=0)
        return edge_index, edge_fea
    
    def __getitem__(self,idx):
        node_fea = self.build_node(idx)
        edge_index, edge_fea = self.build_edge(idx)
        label = self.data[idx][1]
        if self.normalize:
            label = (label - self.label_mean) / self.label_std
        y = torch.tensor([label], dtype=torch.float32)
        data = Data(
            x=node_fea,      
            edge_index=edge_index, 
            edge_attr=edge_fea,
            y=y
        )
        return data
    
'''    
    def build_visualized_graph(self, idx, cutoff=5.0):
        struct = self.struct_list[idx]
        num_atoms = len(struct.sites)
        G = nx.Graph()
        for i in range(num_atoms):
            G.add_node(i, element=struct.sites[i].specie.symbol)
        nbrs = struct.get_all_neighbors(cutoff)
        for center_idx, neighbors in enumerate(nbrs):
            for neighbor in neighbors:
                neighbor_idx = neighbor.index
                if not G.has_edge(center_idx, neighbor_idx):
                   G.add_edge(center_idx, neighbor_idx, distance=neighbor.nn_distance)
        return G
'''    

try:
    tryone = DataTransform(path)
    
    x, edge_index, edge_attr, y = tryone[0].x, tryone[0].edge_index, tryone[0].edge_attr, tryone[0].y
    print(x)
    print(edge_index)
    print(edge_attr)
    print(y)
except Exception as e:
    print(f"运行出错：{e}")


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 1., 0.]])
tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])
tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.,

## Train_test split

In [5]:
from sklearn.model_selection import train_test_split

full_data = DataTransform(path)

train_size = int(0.8 * len(full_data))
test_size = len(full_data) - train_size

train_data, test_data = torch.utils.data.random_split(
    full_data, 
    [train_size, test_size],
    generator=torch.Generator().manual_seed(42)  # 固定随机种子
)

## Dataloader

In [6]:
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32, shuffle=False)

# Step 2- Build CGCNN model using PyTorch Geometric
- Use CGCNNLayer from the paper to build the model
- Use DataTransform class to transform the data into PyG format
- The formulation of CGCNNLayer is as follows:
$$ v_i^{(t+1)}​ = v_i^{(t)} ​+ \sum_{j,k} ​σ(z_{(i,j)_{k}}​^{(t)} ​W_f^{(t)} ​+ b_f^{(t)} ​) \odot g(z_{(i,j)_{k}}​^{(t)} ​W_s{(t)}​ + b_s^{(t)}​)$$
- Use propagate function from PyG to implement the message passing mechanism

In [7]:
class CGCNNLayer(MessagePassing):
    def __init__(
            self, 
            node_dim, 
            edge_dim, 
        ):
        super(CGCNNLayer, self).__init__(aggr = 'add')
        self.l1 = nn.Linear(2 * node_dim + edge_dim, node_dim)
        self.l2 = nn.Linear(2 * node_dim + edge_dim, node_dim)

    def message(self, x_i, x_j, edge_attr):
        z = torch.cat([x_i, x_j, edge_attr], dim=1)
        # attention mechanism
        att = torch.sigmoid(self.l1(z))
        # feature transformation
        feat = F.relu(self.l2(z))
        # element-wise multiplication: attention * feature
        z = att * feat
        return z    

    def update(self, aggr_out, x):
        """aggr_out: adjacent node output; x: node_fea"""
        v = x + aggr_out
        
        return v


    def forward(self, x, edge_index, edge_attr):
        return self.propagate(edge_index, x=x, edge_attr=edge_attr)

# Step 3: Model construction

- Build the CGCNN model using multiple CGCNNLayer layers
- Number of layers:
- - GCNNNLayer: 2
- - Fully connected layers: 2
- - Pooling layer: global mean pooling

In [8]:
class Model(nn.Module):
    def __init__(self, 
                 node_input_dim = node_dim,
                 edge_input_dim = edge_dim,
                 hidden_dim = 64,
                 num_conv_layers = 4,
                 dropout = 0.1
                 ):
        super(Model, self).__init__()

        self.node_embedding = nn.Sequential(
            nn.Linear(node_input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout)
        )
        self.edge_embedding = nn.Sequential(
            nn.Linear(edge_input_dim, hidden_dim),
            nn.ReLU()
        )
        self.conv_layers = nn.ModuleList([
            CGCNNLayer(hidden_dim, hidden_dim) 
            for _ in range(num_conv_layers)
        ])
        self.batch_norms = nn.ModuleList([
            nn.BatchNorm1d(hidden_dim) 
            for _ in range(num_conv_layers)
        ])

        self.fc = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.BatchNorm1d(hidden_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            
            nn.Linear(hidden_dim // 2, 1)
        )

    def forward(self, data):
        x, edge_index, edge_attr = data.x, data.edge_index, data.edge_attr
        batch = data.batch  
        x = self.node_embedding(x)
        edge_attr = self.edge_embedding(edge_attr)
        for conv, bn in zip(self.conv_layers, self.batch_norms):
            identity = x
            x = conv(x, edge_index, edge_attr)
            x = bn(x)
            x = F.relu(x)
            x = x + identity 
        
        x = global_mean_pool(x, batch)
        
        # Output Layer
        x = self.fc(x)
        return x

# Step 4 : Training

## Optimizer and Scheduler

In [9]:
model = Model()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"正在使用的设备: {device}")
model = model.to(device) 

criterion = nn.MSELoss()
criterion = criterion.to(device)  

import torch.optim as optim


optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)

scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=10)



正在使用的设备: cuda


## Early Stopping
AI 加的，早停，减少跑过量的epochs的耗费时间

In [10]:
class EarlyStopping:
    def __init__(self, patience=20, min_delta=0):
        self.patience = patience
        self.min_delta = min_delta
        self.counter = 0
        self.best_loss = None
        self.early_stop = False
        
    def __call__(self, val_loss):
        if self.best_loss is None:
            self.best_loss = val_loss
        elif val_loss > self.best_loss - self.min_delta:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_loss = val_loss
            self.counter = 0

early_stopping = EarlyStopping(patience=20)

In [ ]:
model.train()

epochs = 200
for epoch in range(epochs):
    total_loss = 0.0
    
    for data in train_loader:
        optimizer.zero_grad()
        
        data = data.to(device)
        label = data.y.to(device)
        
        # forward pass
        output = model(data)
        loss = criterion(output.squeeze(), label)

        # backward pass and optimization
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0) # AI 说这里加一个梯度裁剪
        optimizer.step()
        total_loss += loss.item()
    
    avg_loss = total_loss / len(train_loader)
    scheduler.step(avg_loss)  # 根据当前损失调整学习率
    early_stopping(avg_loss)
    if early_stopping.early_stop:
        print(f"Early stopping at epoch {epoch+1}")
        break
    print(f'Epoch [{epoch+1}/{epochs}], Loss: {avg_loss:.4f}')

Epoch [1/200], Loss: 0.6269
Epoch [2/200], Loss: 0.4314
Epoch [3/200], Loss: 0.3382
Epoch [4/200], Loss: 0.2923
Epoch [5/200], Loss: 0.2468
Epoch [6/200], Loss: 0.2838
Epoch [7/200], Loss: 0.2382
Epoch [8/200], Loss: 0.2178
Epoch [9/200], Loss: 0.2297
Epoch [10/200], Loss: 0.2055


# step 5: Testing

这个评估指标是agent写的

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def test(model, loader, dataset, device):
    model.eval()
    predictions = []
    targets = []
    
    with torch.no_grad():
        for data in loader:
            data = data.to(device)
            output = model(data)
            
            # 反归一化
            if hasattr(dataset, 'dataset'):
                label_mean = dataset.dataset.label_mean
                label_std = dataset.dataset.label_std
            else:
                label_mean = dataset.label_mean
                label_std = dataset.label_std
            output = output * label_std + label_mean
            target = data.y * label_std + label_mean
            
            predictions.extend(output.cpu().numpy())
            targets.extend(target.cpu().numpy())
    
    predictions = np.array(predictions).flatten()
    targets = np.array(targets).flatten()
    
    # 计算评估指标
    mae = mean_absolute_error(targets, predictions)
    rmse = np.sqrt(mean_squared_error(targets, predictions))
    r2 = r2_score(targets, predictions)
    
    print(f"\n测试集评估:")
    print(f"  MAE:   {mae:.4f}")
    print(f"  RMSE: {rmse:.4f}")
    print(f"  R²:   {r2:.4f}")
    
    return predictions, targets

# 使用
predictions, targets = test(model, test_loader, test_data, device)

NameError: name 'model' is not defined

In [ ]:
model.eval()
with torch.no_grad():
    for data in test_loader:
        data = data.to(device)
        output = model(data)
        output = output * full_data.label_std + full_data.label_mean
        print(output)

tensor([[ 541.4744],
        [ 454.8799],
        [ 264.2036],
        [ 197.3368],
        [ 723.0032],
        [1981.9058],
        [1299.3427],
        [ 709.2236],
        [ 188.1557],
        [1028.1255],
        [1494.8818],
        [ 583.8770],
        [ 561.4660],
        [ 262.1461],
        [ 638.2465],
        [ 548.0864],
        [ 368.1105],
        [ 472.6346],
        [ 224.9679],
        [ 685.4538],
        [ 195.8480],
        [ 361.9217],
        [ 231.2910],
        [ 456.8365],
        [ 320.1815],
        [ 475.6884],
        [ 959.0400],
        [ 636.2151],
        [ 503.5185],
        [ 636.9849],
        [ 335.1805],
        [1207.1873]], device='cuda:0')
tensor([[ 236.8115],
        [ 193.1265],
        [ 425.6162],
        [ 226.0678],
        [ 358.5158],
        [ 166.6327],
        [ 275.1517],
        [ 858.1161],
        [ 508.5836],
        [ 532.3908],
        [ 577.4448],
        [ 302.4720],
        [ 156.2754],
        [ 266.1908],
        [ 283.06